# ==========================================
# ?? PROD: ??????????
# ==========================================

# 1. ????? (? Docker ??????? 'db' ???)
spring.datasource.url=jdbc:mysql://db:3306/pop_library?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
# ????????????????
spring.datasource.password=123456

# 2. Python AI ???? (? Docker ??????? 'pop_face_system' ???)
python.service.url=http://pop_face_system:8000/api

# 3. ???????? (Linux/Docker ????????????????? /)
# ?? ????????????? Python ????????????? /app/users/ ?
face.image.path=/app/users/
# PROD???????????????????
cors.allowed.origin-patterns=https://n-library.asia, https://www.n-library.asia