# ????? URL??? pop_library ??? Navicat ?????
spring.datasource.url=jdbc:mysql://db:3306/pop_library?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
# MySQL ??
spring.datasource.username=root

# ?????? MySQL ????
spring.datasource.password=123456

# ????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none