# ? ??????????????? (dev)
# ???????????????java -jar app.jar --spring.profiles.active=prod
spring.profiles.active=dev

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none